demo_mysql:
  target: dev
  outputs:
    dev:
      type: mysql
      server: '{{ env_var(''DATABASE_URL'') }}'
      port: 3306  # optional
      database: '{{ env_var(''DATABASE_NAME'') }}' # optional, should be same as schema
      schema: '{{ env_var(''DATABASE_SCHEMA'') }}'
      username: '{{ env_var(''DATABASE_USER'') }}'
      password: '{{ env_var(''DATABASE_PWD'') }}'
      driver: MySQL ODBC 8.0 ANSI Driver